export const items = [
  {
    id: 1,
    file_name: "EratErosViverra.ppt",
    date_added: "11/11/2019",
    folder: "3",
  },
  {
    id: 2,
    file_name: "MorbiNon.mp3",
    date_added: "7/13/2020",
    folder: "2",
  },
  {
    id: 3,
    file_name: "LigulaPellentesque.xls",
    date_added: "1/21/2020",
    folder: "3",
  },
  {
    id: 4,
    file_name: "DuisConsequatDui.xls",
    date_added: "1/4/2020",
    folder: "2",
  },
  {
    id: 5,
    file_name: "SedVelEnim.mp3",
    date_added: "12/27/2019",
    folder: "1",
  },
  {
    id: 6,
    file_name: "Ut.gif",
    date_added: "7/7/2020",
    folder: "1",
  },
  {
    id: 7,
    file_name: "MolestieSedJusto.xls",
    date_added: "2/3/2020",
    folder: "3",
  },
  {
    id: 8,
    file_name: "PedeJusto.tiff",
    date_added: "10/26/2019",
    folder: "3",
  },
  {
    id: 9,
    file_name: "Sed.mp3",
    date_added: "11/7/2019",
    folder: "1",
  },
  {
    id: 10,
    file_name: "VelNisl.xls",
    date_added: "8/26/2019",
    folder: "1",
  },
  {
    id: 11,
    file_name: "Cum.jpeg",
    date_added: "12/6/2019",
    folder: "3",
  },
  {
    id: 12,
    file_name: "SapienUrna.tiff",
    date_added: "7/1/2020",
    folder_name: "2",
  },
  {
    id: 13,
    file_name: "PedeAcDiam.txt",
    date_added: "4/13/2020",
    folder_name: "3",
  },
  {
    id: 14,
    file_name: "Eget.doc",
    date_added: "10/20/2019",
    folder_name: "3",
  },
  {
    id: 15,
    file_name: "AugueVelAccumsan.mp3",
    date_added: "7/17/2020",
    folder_name: "2",
  },
  {
    id: 16,
    file_name: "SedAugueAliquam.ppt",
    date_added: "11/28/2019",
    folder_name: "3",
  },
  {
    id: 17,
    file_name: "RutrumNullaTellus.ppt",
    date_added: "2/23/2020",
    folder_name: "3",
  },
  {
    id: 18,
    file_name: "CubiliaCurae.xls",
    date_added: "8/2/2020",
    folder_name: "1",
  },
  {
    id: 19,
    file_name: "VelDapibus.mp3",
    date_added: "11/15/2019",
    folder_name: "1",
  },
  {
    id: 20,
    file_name: "Maecenas.doc",
    date_added: "6/10/2020",
    folder_name: "2",
  },
  {
    id: 21,
    file_name: "QuamTurpis.xls",
    date_added: "9/29/2019",
    folder_name: "2",
  },
  {
    id: 22,
    file_name: "FelisUtAt.xls",
    date_added: "4/10/2020",
    folder_name: "2",
  },
  {
    id: 23,
    file_name: "CubiliaCurae.xls",
    date_added: "2/11/2020",
    folder_name: "3",
  },
  {
    id: 24,
    file_name: "MontesNasceturRidiculus.xls",
    date_added: "10/2/2019",
    folder_name: "3",
  },
  {
    id: 25,
    file_name: "NuncRhoncusDui.xls",
    date_added: "9/8/2019",
    folder_name: "1",
  },
  {
    id: 26,
    file_name: "AliquamQuisTurpis.ppt",
    date_added: "2/11/2020",
    folder_name: "1",
  },
  {
    id: 27,
    file_name: "PedeAcDiam.mp3",
    date_added: "11/21/2019",
    folder_name: "3",
  },
  {
    id: 28,
    file_name: "Consequat.xls",
    date_added: "4/7/2020",
    folder_name: "2",
  },
  {
    id: 29,
    file_name: "DolorSit.ppt",
    date_added: "12/1/2019",
    folder_name: "3",
  },
  {
    id: 30,
    file_name: "NamCongueRisus.pdf",
    date_added: "7/4/2020",
    folder_name: "2",
  },
  {
    id: 31,
    file_name: "DolorMorbi.png",
    date_added: "8/3/2020",
    folder_name: "1",
  },
  {
    id: 32,
    file_name: "OdioCurabiturConvallis.gif",
    date_added: "8/9/2020",
    folder_name: "2",
  },
  {
    id: 33,
    file_name: "AmetErosSuspendisse.png",
    date_added: "4/20/2020",
    folder_name: "2",
  },
  {
    id: 34,
    file_name: "SapienQuis.mp3",
    date_added: "12/5/2019",
    folder_name: "3",
  },
  {
    id: 35,
    file_name: "SapienDignissimVestibulum.ppt",
    date_added: "11/4/2019",
    folder_name: "2",
  },
  {
    id: 36,
    file_name: "Vulputate.avi",
    date_added: "8/19/2019",
    folder_name: "3",
  },
  {
    id: 37,
    file_name: "Nisl.png",
    date_added: "2/27/2020",
    folder_name: "2",
  },
  {
    id: 38,
    file_name: "VelSemSed.doc",
    date_added: "10/14/2019",
    folder_name: "1",
  },
  {
    id: 39,
    file_name: "Sed.txt",
    date_added: "12/14/2019",
    folder_name: "1",
  },
  {
    id: 40,
    file_name: "PulvinarSed.xls",
    date_added: "8/3/2020",
    folder_name: "1",
  },
  {
    id: 41,
    file_name: "SuscipitNullaElit.gif",
    date_added: "7/23/2020",
    folder_name: "2",
  },
  {
    id: 42,
    file_name: "Et.mp3",
    date_added: "6/21/2020",
    folder_name: "1",
  },
  {
    id: 43,
    file_name: "A.mpeg",
    date_added: "3/11/2020",
    folder: "3",
  },
  {
    id: 44,
    file_name: "Pede.jpeg",
    date_added: "11/19/2019",
    folder: "1",
  },
  {
    id: 45,
    file_name: "UtOdioCras.doc",
    date_added: "10/30/2019",
    folder: "3",
  },
  {
    id: 46,
    file_name: "AtDolorQuis.txt",
    date_added: "8/24/2019",
    folder: "2",
  },
  {
    id: 47,
    file_name: "Integer.doc",
    date_added: "11/27/2019",
    folder: "1",
  },
  {
    id: 48,
    file_name: "AliquamErat.png",
    date_added: "5/7/2020",
    folder: "3",
  },
  {
    id: 49,
    file_name: "Molestie.jpeg",
    date_added: "4/13/2020",
    folder: "2",
  },
  {
    id: 50,
    file_name: "MalesuadaIn.xls",
    date_added: "10/23/2019",
    folder: "3",
  },
];

export const folders = [
  {
    id: 1,
    name: "Folder A",
  },
  {
    id: 2,
    name: "Folder B",
  },
  {
    id: 3,
    name: "Folder C",
  },
];
